replicaCount: 1

image:
  repository: 599138915215.dkr.ecr.us-east-1.amazonaws.com/taskflow-user-service
  tag: 9ebdd3066dd540d062f4653356c4b60119c1d03d
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3001

env:
  NODE_ENV: production
  PORT: "3001"
  DB_HOST: gitops-demo-mysql.caduqm82wpsb.us-east-1.rds.amazonaws.com
  DB_PORT: "3306"
  DB_NAME: users_db
  DB_USER: admin
  JWT_EXPIRES_IN: "7d"

secrets:
  dbPassword: rootpassword
  jwtSecret: your-super-secret-jwt-key

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
