replicaCount: 1

image:
  repository: PLACEHOLDERS
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3002

env:
  NODE_ENV: production
  PORT: "3002"
  DB_HOST: gitops-demo-mysql.caduqm82wpsb.us-east-1.rds.amazonaws.com:3306
  DB_PORT: "3306"
  DB_NAME: tasks_db
  DB_USER: admin
  USER_SERVICE_URL: http://user-service:3001

secrets:
  dbPassword: rootpassword
  jwtSecret: your-super-secret-jwt-key

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
