apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-init
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS users_db;
    CREATE DATABASE IF NOT EXISTS tasks_db;
    GRANT ALL PRIVILEGES ON users_db.* TO 'root'@'%';
    GRANT ALL PRIVILEGES ON tasks_db.* TO 'root'@'%';
    FLUSH PRIVILEGES;
